---
title: "Baromètre ESR - updatedata"
author: "CPESR"
date: "`r Sys.Date()`"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
options(dplyr.summarise.inform = FALSE)
knitr::opts_chunk$set(fig.asp = 9/16, fig.retina = 2)

library(tidyverse)
library(XML)
library(ggcpesrthemes)
theme_set(theme_cpesr())
theme_cpesr_setup(authors = "Julien Gossa", source = "https://github.com/cpesr/RFC/")
```


```{r funs}
root <- xmlRoot(xmlParse(file = "survey_648722_fr.xml"))

qlevels <- function(qgrp,qnum) {
    xmlToDataFrame(root[[4+qgrp]][[2+qnum]][["response"]][["fixed"]])[["label"]]
}
#qlevels(1,1)
#qlevels(3,0)

qsubquestion <- function(qgrp,qnum,qsub) {
  xmlToDataFrame(root[[4+qgrp]][[2+qnum]])[["text"]][[2+qsub]]
}
#qsubquestion(1,1,1)

qtext <- function(qgrp,qnum) {
  xmlValue(root[[4+qgrp]][[2+qnum]][["text"]][[1]])
}
```

## Données 

```{r load}
res <- read.csv("results-survey648722.csv",na.strings=c("","NA"))

colnames(res)
```

```{r comp, results='asis'}
res %>%
  pivot_longer(-id, names_to = "colonne", values_to = "valeur",values_transform = as.character) %>%
  group_by(colonne, renseigné = !is.na(valeur)) %>%
  summarise(nb = n()) %>%
  pivot_wider(names_from = renseigné, values_from = nb, names_prefix = "Renseigné_") %>%
  arrange(desc(Renseigné_TRUE)) %>%
  spoiler_table(trim=Inf, title = "complétion")
```


```{r comp2, results='asis'}
res %>%
  group_by(submitdate_na = is.na(submitdate), lastpage) %>%
  summarise(nb = n()) %>%
  arrange(lastpage) %>%
  ungroup() %>%
  mutate(nbsum = cumsum(nb)) %>%
  spoiler_table(trim=Inf, title = "nb réponses complètes")
```




## Export

```{r export}
results <- res %>%
  rename(anciennete = aciennete) %>%
  rename(confiance.ParitairesLocales. = confiance.ParitainesLocales.) %>%
  #filter(!is.na(submitdate)) %>%
  filter(!is.na(submitdate) | !is.na(conditions.generale.)) %>%
  mutate(across(starts_with("conditions"), ~ factor(.x, levels = qlevels(1,1)))) %>%
  mutate(across(starts_with("evolution"), ~ factor(.x, levels = qlevels(2,0)))) %>%
  mutate(across(starts_with("optimisme"), ~ factor(.x, levels = qlevels(3,0)))) %>%
  mutate(across(starts_with("confiance"), ~ factor(.x, levels = qlevels(4,0)))) %>%
  mutate(across(starts_with("reformes"), ~ factor(.x, levels = qlevels(5,0)))) %>%
  mutate(sexe = factor(sexe, qlevels(6,0))) %>%
  mutate(age = factor(age, qlevels(6,1))) %>%
  mutate(anciennete = factor(anciennete, qlevels(6,2))) %>%
  mutate(metier = factor(metier, qlevels(6,3))) %>%
  mutate(discipline = factor(discipline, qlevels(6,4))) %>%
  mutate(categorie = factor(categorie, qlevels(6,5))) %>%
  mutate(statut = factor(statut, qlevels(6,6))) %>%
  mutate(secteur = factor(secteur, qlevels(6,8))) %>%
  mutate(responsabilites = factor(responsabilites,qlevels(6,10)))


cn <- colnames(results)
conditions.factor <- tibble(
  levels = cn[startsWith(cn,"conditions")] %>% substr(12,50),
  labels = unlist(lapply(1:7, function(x) qsubquestion(1,1,x) )))

confiance.factor <- tibble(
  levels = cn[startsWith(cn,"confiance")] %>% substr(11,50),
  labels = unlist(lapply(0:15, function(x) qsubquestion(4,0,x) )))

reformes.factor <- tibble(
  levels = cn[startsWith(cn,"reformes")] %>% substr(10,50),
  labels = unlist(lapply(1:7, function(x) qsubquestion(5,0,x) )) %>% gsub(", description)",")",.))
#reformes.factor$labels

etab.factor <-tibble(
    levels = unlist(lapply(1:12,function (x) xmlGetAttr(root[[10]][[9]][[x]],"varName"))),
    labels = sapply(3:12,function (x) xmlValue(root[[10]][[9]][[x]][[1]][[1]][[1]][[1]]))) %>%
  mutate(levels = paste0(gsub("_",".",levels),".")) %>%
  mutate(levels = recode(levels, 'typeetabo.' = 'typeetab.other.')) 

## Labels courts

conditions.factor$lab <- c("Général", "Enseignement", "Recherche", 
  "Administration", "Relations", "Carrière", "Vie")

confiance.factor$lab <- c("Etat", "MESRI", "Paritaires Nationales", "CNU", "CoNRS", "ANR", 
"HCERES", "ONR", "FU", "UDICE", "AUREF", "Territoire", 
"Presidences", "CA, CR, CFVU", "Paritaires Locales", "Composante")

reformes.factor$lab <- c("LOLF", "LRU", "Fioraso", "ORE", "LCAP", "LTF", "LPPR")

## Fusions de caractéristiques

results <- results %>%
  mutate(metier.grp = fct_recode(metier,
    `E` = "Personnel d'enseignement", 
    `C` = "Personnel de recherche", 
    `EC` = "Personnel d'enseignement et de recherche", 
    `BIATSS` = "Personnel de bibliothéque", 
    `BIATSS` = "Personnel d'ingénieurie", 
    `BIATSS` = "Personnel administratif", 
    `BIATSS` = "Personnel techno-scientifique", 
    `BIATSS` = "Personnel technique", 
    `BIATSS` = "Personnel social ou de santé")) %>%
  mutate(statut.grp = fct_recode(statut,
    `Titulaire` = "Titulaire d'un poste de la fonction publique", 
    `Contractuel` = "Titulaire d'une chaire professeur junior (CPJ)", 
    `Contractuel` = "Sous contrat CDI", 
    `Contractuel` = "Sous contrat CDD", 
    `Contractuel` = "Sous contrat de mission scientifique", 
    `Contractuel` = "Vacataire ou précaire")) %>%
  mutate(responsabilites.grp = fct_recode(responsabilites,
    `National` = "Membre d'une direction au niveau national ou d'un ministère", 
    `National` = "Membre élu d'une instance nationale", 
    `Etablissement` = "Membre d'une présidence ou d'une direction d'établissement", 
    `Etablissement` = "Membre élu d'un conseil central d'établissement (CA, CR, CFVU...)",
    `Etablissement` = "Membre d'une autre instance centrale d'établissement", 
    `Composante` = "Membre d'une direction de composante ou laboratoire", 
    `Composante` = "Membre d'un conseil de composante ou laboratoire", 
    `Aucune` = "Aucune de ces responsabilités")) %>%
  mutate(categorie.grp = fct_recode(categorie,
    `PR, DR` = "PR, DR ou assimilé ; BIATSS catégorie A ou assimilé", 
    `MCF, CR` = "MCF, CR, PRAG, PRCE ou assimilé ; BIATSS catégorie B ou assimilé",
    `Doc, Post-Doc,\nATER, vacataires` = "Doctorant, post-doctorant, ATER, ATEN, vacataire ou assimilé ; BIASS catégorie C ou assimilé")) %>%
  #mutate(categorie.grp = if_else(metier.grp=="BIATSS",NA,categorie.grp)) %>%
  mutate(anciennete.grp = fct_recode(anciennete,
    `Moins de 5 ans` = "Moins de 5 ans", 
    `De 5 à 9 ans` = "De 5 à 9 ans", 
    `De 10 à 19 ans` = "De 10 à 19 ans", 
    `Au moins 20 ans` = "De 20 à 29 ans", 
    `Au moins 20 ans` = "De 30 à 39 ans", 
    `Au moins 20 ans` = "Au moins 40 ans"
)) %>%
  mutate(discipline.grp = fct_recode(discipline,
    `DEG` = "DEG - Droit, Economie, Gestion", 
    `LLA-SHS` = "LLA-SHS - Lettres, Langues, Arts et Sciences Humaines et Sociales", 
    `STEM` = "STEM - Science, Technologie, Ingénierie et Mathématiques", 
    Santé = "Santé", 
    NULL = "Non-applicable à votre métier")) %>%
  mutate(sexe.grp = fct_recode(sexe,
    NULL = "Autre")) 



## Sauvegarde 
save(results,conditions.factor,confiance.factor,reformes.factor,etab.factor, file="results.RData")

results %>%
  select(conditions.generale.:statut,responsabilites) %>% 
  write.csv("results-anon.csv",row.names = FALSE)
```


## Résumés 

```{r res}
resume <- function(bloc) {
  df <- results %>%
    select(id,starts_with(bloc)) %>%
    pivot_longer(-id, values_to = "Réponse", names_to = "Question") %>%
    filter(!is.na(Réponse)) %>%
    #filter( !startsWith(as.character(Réponse), "Ne connait pas")) %>%
    mutate(Réponse = droplevels(Réponse)) 
  
  l <- levels(df$Réponse)
  
  df <- df %>%
    mutate(Réponse = fct_collapse(Réponse, "Négatif" = l[1:3], "Positif"=l[5:7])) %>%
    summarise(nb.questions = n(), .by=c(Question,Réponse)) %>%
    mutate(part = nb.questions / sum(nb.questions), .by=Question) %>%
    mutate(rang = rank(-part), .by=c(Réponse)) %>%
    mutate(part = scales::percent(part)) %>%
    arrange(Réponse,rang)
    
  
  df <- bind_rows(df %>%
                    summarise(nb.questions = sum(nb.questions), .by=c(Réponse)) %>%
                    mutate(part = scales::percent(nb.questions / sum(nb.questions))),
                  df
  )

  return(df) 
}

# resume("confiance") %>% View()
```


### Condition

```{r rescond}
resume("condition") %>% slice_head(n=4,by=Réponse) %>% kableExtra::kable()
```

### Evolution

```{r resevol}
resume("evolution") %>% slice_head(n=4,by=Réponse) %>% kableExtra::kable()
```

### Optimisme

```{r resopt}
resume("optimisme") %>% slice_head(n=4,by=Réponse) %>% kableExtra::kable()
```

### Confiance

```{r resconf}
resume("confiance") %>% slice_head(n=4,by=Réponse) %>% kableExtra::kable()
```

### Réformes

```{r resref}
resume("reformes") %>% slice_head(n=4,by=Réponse) %>% kableExtra::kable()
```

